version: "3"

services:

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=99
      - PGID=100
      - VERSION=docker
    volumes:
      - ./plex:/config
      - /mnt/user/media:/mnt/user/media
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge:5b398f77-ls22  #bfbdbd96147a
    container_name: deluge
    network_mode: host
    environment:
      - PUID=99
      - PGID=100
      - UMASK_SET=022
      - TZ=America/Santiago
      - 8112:8112
      - 58846:58846
      - 58846:58846/udp
    volumes:
      - ./deluge:/config
      - /mnt/user/media:/mnt/user/media
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Santiago
    volumes:
      - ./tautulli:/config
      - ./plex/Library/Application Support/Plex Media Server/Logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped


  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Santiago
    volumes:
      - ./sonarr:/config
      - /mnt/user/media:/mnt/user/media
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Santiago
    volumes:
      - ./radarr:/config
      - /mnt/user/media:/mnt/user/media
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Santiago
    volumes:
      - ./lidarr:/config
      - /mnt/user/media:/mnt/user/media
    ports:
      - 8686:8686
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Santiago
    volumes:
      - ./jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Santiago
    volumes:
      - ./bazarr:/config
      - /mnt/user/media:/mnt/user/media
    ports:
      - 6767:6767
    restart: unless-stopped


    
